<?php
/**
 * TL_ROOT/system/modules/bookmarking/languages/de/default.php 
 * 
 * TYPOlight extension: bookmarking 1.0.1 stable 
 * Deutsch translation file 
 * 
 * Copyright : &copy; Helmut Schottmüller 
 * License   : GNU Lesser Public License (LGPL) 
 * Author    : Helmut Schottmüller (hschottm), http://www.aurealis.de 
 * Translator: Helmut Schottmüller (hschottm), http://www.aurealis.de 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['CTE']['bookmarking']['0'] = "Social Bookmarks (Soziale Lesezeichen)";
$GLOBALS['TL_LANG']['CTE']['bookmarking']['1'] = "Dieses Inhaltselement erstellt einen oder mehrere Hyperlinks, um die aktuelle Seite als Lesezeichen bei einem Social Bookmark Anbieter abzulegen.";
 
?>
