<?php
/**
 * TL_ROOT/system/modules/bookmarking/languages/de/tl_content.php 
 * 
 * TYPOlight extension: bookmarking 1.0.1 stable 
 * Deutsch translation file 
 * 
 * Copyright : &copy; Helmut Schottmüller 
 * License   : GNU Lesser Public License (LGPL) 
 * Author    : Helmut Schottmüller (hschottm), http://www.aurealis.de 
 * Translator: Helmut Schottmüller (hschottm), http://www.aurealis.de 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_content']['bookmarking']['0'] = "Social Bookmark Anbieter";
$GLOBALS['TL_LANG']['tl_content']['bookmarking']['1'] = "Bitte wählen Sie einen oder mehrere Social Bookmark Anbieter aus, auf die auf der aktuellen Seite verwiesen werden soll.";
$GLOBALS['TL_LANG']['tl_content']['bookmarking']['delicious']['0'] = "delicious";
$GLOBALS['TL_LANG']['tl_content']['bookmarking']['delicious']['1'] = "delicious (<a href=\"http://del.icio.us/\">http://del.icio.us/</a>)";
$GLOBALS['TL_LANG']['tl_content']['bookmarking']['digg']['0'] = "digg";
$GLOBALS['TL_LANG']['tl_content']['bookmarking']['digg']['1'] = "digg (<a href=\"http://digg.com/\">http://digg.com/</a>)";
$GLOBALS['TL_LANG']['tl_content']['bookmarking']['furl']['0'] = "furl";
$GLOBALS['TL_LANG']['tl_content']['bookmarking']['furl']['1'] = "furl (<a href=\"http://www.furl.net/\">http://www.furl.net/</a>)";
$GLOBALS['TL_LANG']['tl_content']['bookmarking']['stumbleupon']['0'] = "StumbleUpon";
$GLOBALS['TL_LANG']['tl_content']['bookmarking']['stumbleupon']['1'] = "StumbleUpon (<a href=\"http://www.stumbleupon.com/\">http://www.stumbleupon.com/</a>)";
$GLOBALS['TL_LANG']['tl_content']['bookmarking']['wong']['0'] = "Mister Wong";
$GLOBALS['TL_LANG']['tl_content']['bookmarking']['wong']['1'] = "Mister Wong (<a href=\"http://www.mister-wong.de/\">http://www.mister-wong.de/</a>)";
$GLOBALS['TL_LANG']['tl_content']['bookmarking_addthis']['0'] = "AddThis";
$GLOBALS['TL_LANG']['tl_content']['bookmarking_addthis']['1'] = "Wählen Sie diese Option aus, um den AddThis-Dienst verfügbar zu machen. AddThis fügt die aktuelle Seite in alle bekannten Social Bookmark Angebote ein. (<a href=\"http://www.addthis.com\">http://www.addthis.com</a>)";
$GLOBALS['TL_LANG']['tl_content']['bookmarking_addthis_publisher']['0'] = "AddThis Zugang";
$GLOBALS['TL_LANG']['tl_content']['bookmarking_addthis_publisher']['1'] = "Bitte geben Sie den Namen des AddThis Zugangs ein, über den die Bookmarks veröffentlicht werden sollen. Dies dient ausschließlich statistischen Zwecken.";
$GLOBALS['TL_LANG']['tl_content']['bookmark_delicious'] = "Diese Seite zu Delicious hinzufügen";
$GLOBALS['TL_LANG']['tl_content']['bookmark_digg'] = "digg it";
$GLOBALS['TL_LANG']['tl_content']['bookmark_furl'] = "Diese Seite zu Furl hinzufügen";
$GLOBALS['TL_LANG']['tl_content']['bookmark_stumbleupon'] = "Stumble diese Seite!";
$GLOBALS['TL_LANG']['tl_content']['bookmark_wong'] = "Diese Seite zu Mister Wong hinzufügen";
$GLOBALS['TL_LANG']['tl_content']['bookmarking_legend'] = "Social Bookmark Anbieter";
$GLOBALS['TL_LANG']['tl_content']['addthis_legend'] = "AddThis-Einstellungen";
 
?>
